#!/usr/bin/env python3
"""Regenerate static entries from the shared model and background catalogs."""
import argparse
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CHARACTERS = ['chocola', 'vanilla', 'azuki', 'coconut', 'maple', 'cinnamon', 'milk', 'fraise']


def js(value):
    return json.dumps(value, ensure_ascii=False, separators=(',', ':')).replace('<', '\\u003c')


def generate(mode):
    catalog = json.loads((ROOT / 'config/model-catalog.json').read_text())
    presentation = json.loads((ROOT / 'config/model-presentation.json').read_text())
    names = json.loads((ROOT / 'config/background-names.json').read_text())
    models = {key: dict(model, id=key, presentation=presentation.get(key, {})) for key, model in catalog.items()}
    backgrounds = []
    extensions = {'.png', '.jpg', '.jpeg', '.gif', '.webp', '.bmp'}
    for image in sorted((ROOT / 'background').iterdir()):
        if image.is_file() and image.suffix.lower() in extensions:
            backgrounds.append(dict(id=image.name, type='static', image=image.name, names=names.get(image.name, {})))
    groups = {}
    for image in sorted((ROOT / 'background/dynamic').iterdir()):
        if image.is_file() and image.suffix.lower() in extensions and image.stem[-1:].upper() in 'ABC':
            groups.setdefault(image.stem[:-1], {})[image.stem[-1].upper()] = 'dynamic/' + image.name
    for scene, images in sorted(groups.items()):
        if set(images) == {'A', 'B', 'C'}:
            backgrounds.append(dict(id='dynamic/' + scene, type='dynamic', images=images, names=names.get(scene, {})))
    (ROOT / 'config/background-catalog.js').write_text(
        '// Generated by scripts/generate-static.py; edit background/ and background-names.json.\n'
        + 'window.NekoWallpapers = ' + js(backgrounds) + ';\n'
        + 'window.NekoDefaultWallpaper = ' + js(backgrounds[0]['id'] if backgrounds else None) + ';\n')
    if mode == 'single':
        (ROOT / 'config/model-catalog.js').write_text(
            '// Generated by scripts/generate-static.py; edit model-catalog.json and model-presentation.json.\n'
            + 'window.NekoModels = ' + js(models) + ';\n'
            + 'window.NekoCurrentModel = window.NekoModels["chocola-lolita"];\n')

    def page(current):
        single = mode == 'single'
        scripts = ['<script src="./config/reaction-library.js" charset="UTF-8"></script>']
        if single:
            scripts.append('<script>window.NekoConfigs = Object.create(null);</script>')
            scripts.extend('<script src="./config/' + name + '" charset="UTF-8"></script>'
                           for name in sorted({m['config'] for m in catalog.values()}))
            scripts.append('<script src="./config/model-catalog.js" charset="UTF-8"></script>')
        else:
            scripts.append('<script src="./config/' + catalog[current]['config'] + '" charset="UTF-8"></script>')
            scripts.append('<script>window.NekoCurrentModel = ' + js(models[current]) + ';</script>')
        menu = []
        for character in CHARACTERS:
            menu.append('    <div class="menu-item">\n      <span class="label" data-i18n="' + character + '">' + character.capitalize() + '</span>\n      <div class="dropdown">')
            for key, model in catalog.items():
                if model['character'] != character:
                    continue
                href = '#' + key if single else './' + key + '.html'
                attrs = ' data-model="./data/' + key + '.pure.psb.zip" data-config="' + model['config'].removesuffix('-config.js') + '"' if single else ' data-model="' + key + '"'
                active = '' if single or key != current else ' aria-current="page"'
                label = '<span data-i18n="' + model['costume'] + '">' + html.escape(model['costume']) + '</span>'
                label += ''.join(' · <span data-i18n="variant-' + v + '">' + html.escape(v) + '</span>' for v in model['variants'])
                menu.append('        <a href="' + href + '"' + attrs + active + '>' + label + '</a>')
            menu.append('      </div>\n    </div>')
        heap = '  <!-- One fixed heap shared by all model sessions. -->\n  <script>var EmoteModule = { TOTAL_MEMORY: 256 * 1024 * 1024 };</script>\n' if single else ''
        onload = '' if single else ' onload="start(\'./data/' + current + '.pure.psb.zip\')"'
        status = '    <div id="character-status" role="status" aria-live="polite"></div>\n' if single else ''
        switcher = '  <script src="character-switcher.js" charset="UTF-8"></script>\n' if single else ''
        return '''<!DOCTYPE html>
<!-- Generated by scripts/generate-static.py. -->
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="一个可以在浏览器中展示猫娘乐园角色E-mote动态立绘的项目，可以用做桌面动态壁纸。">
  <title>猫娘乐园角色E-mote图鉴</title>
  <link rel="icon" href="neko.png" type="image/png">
  <link rel="stylesheet" href="ui.css">
''' + heap + '''  <script src="./driver/FreeMoteDriver.js" charset="UTF-8"></script>
  <script src="./driver/emoteplayer.js" charset="UTF-8"></script>
  ''' + '\n  '.join(scripts) + '''
  <script src="./locales.js" charset="UTF-8"></script>
  <script src="main.js" charset="UTF-8"></script>
  <script src="fflate.js" charset="UTF-8"></script>
  <script src="./config/background-catalog.js" charset="UTF-8"></script>
  <script src="./background.js" charset="UTF-8"></script>
</head>
<body''' + onload + '''>
  <canvas id="canvas"></canvas>
  <div id="loading" data-i18n="loading">Loading...</div>
  <img id="toggle-icon" src="neko.png" alt="Toggle Topbar" />
  <div id="topbar">
    <div class="label" data-i18n="pageTitle" style="font-weight:bold; font-size:18px; color:#6f4e37;">猫娘乐园角色E-mote图鉴</div>
''' + '\n'.join(menu) + '\n' + status + '''    <div class="infotext" data-i18n="by" data-i18n-params='{"author": "GTX690战术核显卡导弹"}'>By： <a href="https://www.nekopara.uk" target="_blank">GTX690战术核显卡导弹</a></div>
    <div class="infotext" data-i18n="githubProject" data-i18n-params='{"project": "NekoWebShow"}'>Github Project: <a href="https://github.com/Chocola-X/NekoWebShow" target="_blank">NekoWebShow</a></div>
  </div>
  <script src="ui.js" charset="UTF-8"></script>
''' + switcher + '''</body>
</html>
'''

    (ROOT / 'index.html').write_text(page('chocola-lolita'))
    if mode == 'multi':
        # Remove obsolete pages produced by this generator when model IDs change.
        for old_page in ROOT.glob('*.html'):
            if old_page.stem != 'index' and old_page.stem not in catalog:
                if '<!-- Generated by scripts/generate-static.py. -->' in old_page.read_text():
                    old_page.unlink()
        for key in catalog:
            (ROOT / (key + '.html')).write_text(page(key))
    print(f'Generated {len(catalog)} models and {len(backgrounds)} backgrounds ({mode}).')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--mode', choices=['multi', 'single'], required=True)
    generate(parser.parse_args().mode)
